version: '3'

services:
  lt_client:
    build: ./LiveTelemetry_client
    container_name: lt_client
    ports:
      - '3000:3000'
    networks:
      - mynetwork

  lt_server:
    build: ./LiveTelemetry_server
    container_name: lt_server
    ports:
      - '3002:3002'
    stdin_open: true
    tty: true
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: liveTelemetry_db
      MYSQL_ROOT_PASSWORD: SkillIssue!2023
      MYSQL_USER: admin
      MYSQL_PASSWORD: SkillIssue!2023
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_PASSWORD: SkillIssue!2023
    ports:
      - "8080:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge